rnd_face_recognitive/Models/ErrorViewModel.cs
using System;

namespace rnd_face_recognitive.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

rnd_face_recognitive/Controllers/FotoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using rnd_face_recognitive.Models;
using Microsoft.Azure.CognitiveServices.Vision.Face;
using Microsoft.Azure.CognitiveServices.Vision.Face.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using rnd_face_recognitive.Data;

namespace rnd_face_recognitive.Controllers
{
    public class FotoController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private PersonGroup personGroup;
        IFaceClient faceClient = Authenticate("https://westcentralus.api.cognitive.microsoft.com/", "406ba95805ca490facda8b6cd7f0381c");
        private readonly DataBaseContext _myDbContext = new DataBaseContext();
        public FotoController(ILogger<HomeController> logger)
        {
            _logger = logger;
            personGroup = new PersonGroup()
            {
                PersonGroupId = "gits",
                Name = "GITS",
                RecognitionModel = "recognition_02"
            };

            using (var listGroup = faceClient.PersonGroup.ListAsync())
            {
                if (!listGroup.Result.Contains(personGroup))
                {
                    faceClient.PersonGroup.CreateAsync(personGroup.PersonGroupId, personGroup.Name, recognitionModel: "recognition_02");
                }
            }
        }

        public static IFaceClient Authenticate(string endpoint, string key)
        {
            return new FaceClient(new ApiKeyServiceClientCredentials(key)) { Endpoint = endpoint };
        }

        public IActionResult TakeFoto()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CaptureAsync()
        {
            try
            {
                var files = HttpContext.Request.Form.Files;

                if (files != null)
                {
                    foreach (var file in files)
                    {
                        Guid unique = Guid.NewGuid();

                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\foto", unique.ToString() + ".jpeg");

                        var result = await faceClient.Face.DetectWithStreamAsync(file.OpenReadStream(), true, true, recognitionModel: "recognition_02", returnRecognitionModel: true);

                        if (result.Count > 0)
                        {
                            //register foto
                            var result2 = await faceClient.PersonGroupPerson.CreateAsync(personGroup.PersonGroupId, result[0].FaceId.Value.ToString());
                            var result3 = await faceClient.PersonGroupPerson.AddFaceFromStreamAsync(personGroup.PersonGroupId, result2.PersonId, file.OpenReadStream());

                            using (var stream = new FileStream(path, FileMode.Create))
                            {
                                file.CopyTo(stream);
                                //save database
                                _myDbContext.persons.Add(new Data.Person()
                                {
                                    Id = result2.PersonId,
                                    Path = Path.Combine("foto", unique + ".jpeg")
                                });
                                _myDbContext.SaveChanges();
                            }
                        }
                        else
                        {
                            return Json("Gagal upload, itu muka atau sendal jepit");
                        }
                    }
                }

                return Json("Sukses");
            }
            catch (Exception) { throw; }
        }

        public IActionResult CekMuka()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PostCekMuka()
        {
            try
            {
                var files = HttpContext.Request.Form.Files;
                if (files != null)
                {
                    foreach (var file in files)
                    {
                        //train
                        await faceClient.PersonGroup.TrainAsync(personGroup.PersonGroupId);

                        TrainingStatus trainingStatus = null;
                        while (true)
                        {
                            trainingStatus = await faceClient.PersonGroup.GetTrainingStatusAsync(personGroup.PersonGroupId);

                            if (trainingStatus.Status != TrainingStatusType.Running)
                            {
                                break;
                            }

                            await Task.Delay(1000);
                        }

                        var faces = await faceClient.Face.DetectWithStreamAsync(file.OpenReadStream());
                        if (faces.Count > 0)
                        {
                            List<Guid> faceIds = faces.Select(face => face.FaceId.Value).ToList();
                            var results = await faceClient.Face.IdentifyAsync(faceIds, personGroup.PersonGroupId, maxNumOfCandidatesReturned: 5);
                            if (results.Count > 0)
                            {
                                foreach (var identifyResult in results)
                                {
                                    if (identifyResult.Candidates.Count == 0)
                                    {
                                        return Json("Muka kamu kesepian, take foto dulu sana");
                                    }
                                    else
                                    {
                                        var listFoto = _myDbContext.persons.Where(x => identifyResult.Candidates.Select(f => f.PersonId).ToList().Contains(x.Id)).ToList();
                                        return Json(string.Join(',', listFoto.Select(x=>x.Path).ToList()));
                                    }
                                }
                            }
                            else
                            {
                                return Json("Muka kamu kesepian, take foto dulu sana");
                            }
                        }
                        else
                        {
                            return Json("gagal, muka kamu kaya rambutan");
                        }
                    }
                }

                return Json("Foto kosong");
            }
            catch (Exception e)
            {
                throw;
            }
        }
    }
}

rnd_face_recognitive/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using rnd_face_recognitive.Models;
using Microsoft.Azure.CognitiveServices.Vision.Face;
using Microsoft.Azure.CognitiveServices.Vision.Face.Models;

namespace rnd_face_recognitive.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

rnd_face_recognitive/Views/Foto/CekMuka.cshtml
@{
    ViewData["Title"] = "CekMuka";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Camera</div>
            <div class="panel-body">
                <div id="my_camera"></div>
                <!-- A button for taking snaps -->
                <form>
                    <input type="button" class="btn btn-success" value="Take Snapshot" onClick="take_snapshot()">
                </form>
                <div id="results"></div>
            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">muka yang sama</div>
            <div class="panel-body">
                <div id="resultsMuka">Your captured image will appear here...</div>
            </div>
            <br />
            <br />
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
@section scripts{
    <script type="text/javascript" src="~/webcamjs/webcam.min.js"></script>
    <script language="JavaScript">
        Webcam.set({
            width: 420,
            height: 340,
            image_format: 'jpeg',
            jpeg_quality: 180
        });
        Webcam.attach('#my_camera');
    </script>
    <!-- Code to handle taking the snapshot and displaying it locally -->
    <script language="JavaScript">
        function take_snapshot() {
            // take snapshot and get image data
            Webcam.snap(function (data_uri) {
                // display results in page
                swal("Loading", {
                    button: false,
                    closeOnClickOutside: false,
                });
                document.getElementById('results').innerHTML = '<img hidden id="imageprev" src="' + data_uri + '"/>';

                var base64image = document.getElementById("imageprev").src;
                Webcam.upload(base64image,
                    '/Foto/PostCekMuka',
                    function (code, text) {
                        var str = '';

                        text = text.replace('"', '');
                        text.split(/\s*,\s*/).forEach(function(fotoFile) {
                            str = str + '<img height="150" src="/' + fotoFile + '"/>';
                        });
                        document.getElementById('resultsMuka').innerHTML = str;
                        swal('sukses');
                    });
            });
        }
    </script>

}

rnd_face_recognitive/Views/Foto/TakeFoto.cshtml
@{
    ViewData["Title"] = "TakeFoto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<button class="btn" disabled>ascasc</button>
<button class="btn disabled">ascasc</button>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Camera</div>
            <div class="panel-body">
                <div id="my_camera"></div>
                <!-- A button for taking snaps -->
                <form>
                    <input type="button" class="btn btn-success" value="Take Snapshot" onClick="take_snapshot()">
                </form>

            </div>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Captured Photo</div>
            <div class="panel-body">
                <div id="results">Your captured image will appear here...</div>
            </div>
            <br />
            <br />
        </div>
    </div>
    <div class="col-md-3"></div>
</div>

@section scripts{
    <script type="text/javascript" src="~/webcamjs/webcam.min.js"></script>
    <script language="JavaScript">
        Webcam.set({
            width: 420,
            height: 340,
            image_format: 'jpeg',
            jpeg_quality: 180
        });
        Webcam.attach('#my_camera');
    </script>
    <!-- Code to handle taking the snapshot and displaying it locally -->
    <script language="JavaScript">
        function take_snapshot() {
            // take snapshot and get image data
            Webcam.snap(function (data_uri) {
                swal("Loading", {
                    button: false,
                    closeOnClickOutside: false,
                });
                // display results in page
                document.getElementById('results').innerHTML = '<img id="imageprev" src="' + data_uri + '"/>';

                var base64image = document.getElementById("imageprev").src;
                Webcam.upload(base64image,
                    '/Foto/Capture',
                    function (code, text) {
                        swal(text);
                    });
            });
        }
    </script>

}

rnd_face_recognitive/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

rnd_face_recognitive/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - rnd_face_recognitive</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">rnd_face_recognitive</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Foto" asp-action="TakeFoto">Take Foto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Foto" asp-action="CekMuka">Cek Muka</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - rnd_face_recognitive - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>